<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>BAC Secretariat Reports | PaperTrail</title>
    <link rel="stylesheet" href="{{ asset('css/landing.css') }}">
</head>
<body class="print-body">
    @php
        $money = fn ($amount) => 'PHP ' . number_format((float) $amount, 2);
        $label = fn ($value) => $value ? str($value)->replace('_', ' ')->title() : 'N/A';
        $activeFilters = collect($filters)->filter(fn ($value) => filled($value));
    @endphp

    <main class="print-report">
        <header class="print-header">
            <p>PaperTrail</p>
            <h1>BAC Secretariat Reports</h1>
            <span>{{ $lguName }}</span>
            <span>Generated by {{ auth()->user()?->name }} on {{ now()->format('M d, Y h:i A') }}</span>
        </header>

        <section class="print-summary">
            <div><strong>Incoming:</strong> {{ $summary['incoming'] }}</div>
            <div><strong>Routed:</strong> {{ $summary['routed'] }}</div>
            <div><strong>APP:</strong> {{ $summary['apps'] }}</div>
            <div><strong>PR:</strong> {{ $summary['prs'] }}</div>
            <div><strong>PO:</strong> {{ $summary['pos'] }}</div>
            <div><strong>Returned:</strong> {{ $summary['returned'] }}</div>
            <div><strong>Completed:</strong> {{ $summary['completed'] }}</div>
            <div><strong>Total Amount:</strong> {{ $money($summary['amount']) }}</div>
        </section>

        <section class="print-summary">
            <div><strong>Filters:</strong>
                @if ($activeFilters->isEmpty())
                    All records
                @else
                    {{ $activeFilters->map(fn ($value, $key) => str($key)->replace('_', ' ')->title() . ': ' . $value)->implode(' | ') }}
                @endif
            </div>
        </section>

        <h2>Incoming Documents Summary</h2>
        <table class="print-table">
            <thead><tr><th>Tracking Number</th><th>Type</th><th>Office</th><th>Amount</th><th>Status</th><th>Updated</th></tr></thead>
            <tbody>
                @forelse ($incoming as $document)
                    <tr>
                        <td>{{ $document->displayNumber() }}</td>
                        <td>{{ $document->document_type }}</td>
                        <td>{{ $document->submittingOffice?->name ?? 'N/A' }}</td>
                        <td>{{ $money($document->total_amount) }}</td>
                        <td>{{ $label($document->status) }}</td>
                        <td>{{ $document->updated_at?->format('M d, Y') }}</td>
                    </tr>
                @empty
                    <tr><td colspan="6">No incoming records found.</td></tr>
                @endforelse
            </tbody>
        </table>

        <h2>Document Routing Summary</h2>
        <table class="print-table">
            <thead><tr><th>Tracking Number</th><th>Title</th><th>Stage</th><th>Latest Action By</th><th>Date</th><th>Status</th></tr></thead>
            <tbody>
                @forelse ($routing as $document)
                    @php $latestHistory = $document->routingHistories->first(); @endphp
                    <tr>
                        <td>{{ $document->displayNumber() }}</td>
                        <td>{{ $document->title }}</td>
                        <td>{{ $document->stage ?? 'N/A' }}</td>
                        <td>{{ $latestHistory?->actionBy?->name ?? 'N/A' }}</td>
                        <td>{{ $latestHistory?->action_at?->format('M d, Y') ?? $document->routed_at?->format('M d, Y') ?? 'N/A' }}</td>
                        <td>{{ $label($document->status) }}</td>
                    </tr>
                @empty
                    <tr><td colspan="6">No routing records found.</td></tr>
                @endforelse
            </tbody>
        </table>

        <h2>APP Consolidation Summary</h2>
        <table class="print-table">
            <thead><tr><th>Tracking Number</th><th>APP No.</th><th>Fiscal Year</th><th>Title</th><th>Items</th><th>Amount</th><th>Status</th></tr></thead>
            <tbody>
                @forelse ($apps as $app)
                    <tr>
                        <td>{{ $app->displayNumber() }}</td>
                        <td>{{ $app->app_number ?? 'Draft' }}</td>
                        <td>{{ $app->fiscal_year }}</td>
                        <td>{{ $app->title }}</td>
                        <td>{{ $app->appItems->count() }}</td>
                        <td>{{ $money($app->total_amount) }}</td>
                        <td>{{ $label($app->status) }}</td>
                    </tr>
                @empty
                    <tr><td colspan="7">No APP records found.</td></tr>
                @endforelse
            </tbody>
        </table>

        <h2>Purchase Requests Summary</h2>
        <table class="print-table">
            <thead><tr><th>Tracking Number</th><th>Official PR No.</th><th>Office</th><th>Title</th><th>Amount</th><th>PR Status</th><th>Status</th></tr></thead>
            <tbody>
                @forelse ($prs as $document)
                    <tr>
                        <td>{{ $document->displayNumber() }}</td>
                        <td>{{ $document->pr_no ?? 'N/A' }}</td>
                        <td>{{ $document->submittingOffice?->name ?? 'N/A' }}</td>
                        <td>{{ $document->title ?? $document->purpose }}</td>
                        <td>{{ $money($document->total_amount) }}</td>
                        <td>{{ $label($document->pr_status) }}</td>
                        <td>{{ $label($document->status) }}</td>
                    </tr>
                @empty
                    <tr><td colspan="7">No purchase request records found.</td></tr>
                @endforelse
            </tbody>
        </table>

        <h2>Purchase Orders Summary</h2>
        <table class="print-table">
            <thead><tr><th>Tracking Number</th><th>PO No.</th><th>Source PR</th><th>Supplier</th><th>Office</th><th>Amount</th><th>Status</th></tr></thead>
            <tbody>
                @forelse ($pos as $po)
                    <tr>
                        <td>{{ $po->displayNumber() }}</td>
                        <td>{{ $po->po_number ?? 'Draft' }}</td>
                        <td>{{ $po->sourcePrDocument?->displayNumber() ?? 'N/A' }}</td>
                        <td>{{ $po->supplier_name ?? 'N/A' }}</td>
                        <td>{{ $po->sourcePrDocument?->submittingOffice?->name ?? 'N/A' }}</td>
                        <td>{{ $money($po->total_amount) }}</td>
                        <td>{{ $label($po->status) }}</td>
                    </tr>
                @empty
                    <tr><td colspan="7">No purchase order records found.</td></tr>
                @endforelse
            </tbody>
        </table>

        <h2>Returned Documents Summary</h2>
        <table class="print-table">
            <thead><tr><th>Tracking Number</th><th>Type</th><th>Office</th><th>Remarks</th><th>Date</th><th>Status</th></tr></thead>
            <tbody>
                @forelse ($returned as $document)
                    @php $latestReturn = $document->routingHistories->first(); @endphp
                    <tr>
                        <td>{{ $document->displayNumber() }}</td>
                        <td>{{ $document->document_type }}</td>
                        <td>{{ $document->submittingOffice?->name ?? 'N/A' }}</td>
                        <td>{{ $latestReturn?->comments ?? $document->remarks ?? $document->bac_secretariat_remarks ?? 'N/A' }}</td>
                        <td>{{ $latestReturn?->action_at?->format('M d, Y') ?? $document->updated_at?->format('M d, Y') }}</td>
                        <td>{{ $label($document->status) }}</td>
                    </tr>
                @empty
                    <tr><td colspan="6">No returned records found.</td></tr>
                @endforelse
            </tbody>
        </table>

        <h2>Monthly Activity Summary</h2>
        <table class="print-table">
            <thead><tr><th>Month</th><th>Incoming</th><th>Routed</th><th>APPs</th><th>PRs</th><th>PO Issued</th><th>PO Completed</th><th>Returned</th></tr></thead>
            <tbody>
                @forelse ($monthly as $month => $data)
                    <tr>
                        <td>{{ $month }}</td>
                        <td>{{ $data['incoming'] }}</td>
                        <td>{{ $data['routed'] }}</td>
                        <td>{{ $data['apps'] }}</td>
                        <td>{{ $data['prs'] }}</td>
                        <td>{{ $data['poIssued'] }}</td>
                        <td>{{ $data['poCompleted'] }}</td>
                        <td>{{ $data['returned'] }}</td>
                    </tr>
                @empty
                    <tr><td colspan="8">No monthly activity found.</td></tr>
                @endforelse
            </tbody>
        </table>

        <h2>Office Request Summary</h2>
        <table class="print-table">
            <thead><tr><th>Office</th><th>Documents</th><th>PRs</th><th>Returned</th><th>Completed</th><th>Amount</th></tr></thead>
            <tbody>
                @forelse ($officeSummary as $office => $data)
                    <tr>
                        <td>{{ $office }}</td>
                        <td>{{ $data['documents'] }}</td>
                        <td>{{ $data['prs'] }}</td>
                        <td>{{ $data['returned'] }}</td>
                        <td>{{ $data['completed'] }}</td>
                        <td>{{ $money($data['amount']) }}</td>
                    </tr>
                @empty
                    <tr><td colspan="6">No office summary found.</td></tr>
                @endforelse
            </tbody>
        </table>

        <footer class="print-footer">
            PaperTrail BAC Secretariat report generated from existing system records only.
        </footer>
    </main>
</body>
</html>
