<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BAC Chair Reports | PaperTrail</title>
    <link rel="stylesheet" href="{{ asset('css/landing.css') }}">
    <style>
        body { background: #fff; color: #111827; }
        .print-report { max-width: 1120px; margin: 0 auto; padding: 32px; }
        .print-header { border-bottom: 2px solid #0b2341; margin-bottom: 18px; padding-bottom: 14px; }
        .print-header p { margin: 4px 0; color: #4b5563; }
        .print-summary { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin: 18px 0; }
        .print-summary div { border: 1px solid #e5e7eb; padding: 10px; }
        .print-section { margin-top: 22px; page-break-inside: avoid; }
        table { width: 100%; border-collapse: collapse; font-size: 12px; }
        th, td { border: 1px solid #d1d5db; padding: 7px; text-align: left; vertical-align: top; }
        th { background: #f3f4f6; }
        @media print { .no-print { display: none; } .print-report { padding: 0; } }
    </style>
</head>
<body>
    @php
        $label = fn ($value) => $value ? str($value)->replace('_', ' ')->title() : 'N/A';
        $money = fn ($amount) => 'PHP ' . number_format((float) $amount, 2);
    @endphp
    <main class="print-report">
        <button class="dashboard-action no-print" onclick="window.print()">Print</button>
        <header class="print-header">
            <p class="eyebrow">PaperTrail Internal Report</p>
            <h1>BAC Chair Reports</h1>
            <p>{{ $lguName }}</p>
            <p>Generated by {{ $generatedBy }} on {{ $generatedAt->format('M d, Y h:i A') }}</p>
        </header>

        <section class="print-section">
            <h2>Filter Summary</h2>
            @foreach ($filterSummary as $name => $value)
                <p><strong>{{ $name }}:</strong> {{ $value }}</p>
            @endforeach
        </section>

        <section class="print-summary">
            <div><strong>{{ $summary['pendingApprovals'] }}</strong><br>Pending BAC Approvals</div>
            <div><strong>{{ $summary['forConfirmation'] }}</strong><br>Documents for Confirmation</div>
            <div><strong>{{ $summary['confirmed'] }}</strong><br>Confirmed Documents</div>
            <div><strong>{{ $summary['returned'] }}</strong><br>Returned Documents</div>
            <div><strong>{{ $summary['forwarded'] }}</strong><br>Forwarded to HOPE</div>
            <div><strong>{{ $summary['reviewedThisMonth'] }}</strong><br>Reviewed This Month</div>
        </section>

        <section class="print-section">
            <h2>Report Records</h2>
            <table>
                <thead>
                    <tr>
                        @foreach ($headers as $header)
                            <th>{{ $header }}</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @forelse ($exportRows->take(200) as $document)
                        <tr>
                            @foreach (app(\App\Http\Controllers\BacChair\ReportController::class)->mapRow($document) as $column)
                                <td>{{ $column }}</td>
                            @endforeach
                        </tr>
                    @empty
                        <tr><td colspan="{{ count($headers) }}">No report data available.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </section>

        <footer class="print-section">
            <p>PaperTrail Internal Report</p>
        </footer>
    </main>
</body>
</html>
