<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $title }} | PaperTrail</title>
    <style>
        body {
            color: #0b2341;
            font-family: Arial, sans-serif;
            margin: 28px;
        }

        header {
            border-bottom: 2px solid #0b2341;
            margin-bottom: 18px;
            padding-bottom: 12px;
        }

        h1 {
            font-size: 22px;
            margin: 0 0 4px;
        }

        h2 {
            font-size: 15px;
            margin: 18px 0 8px;
        }

        p {
            margin: 0;
        }

        .meta,
        .filters,
        footer {
            color: #4b5563;
            font-size: 12px;
            line-height: 1.5;
        }

        .filters,
        .summary {
            margin: 12px 0 18px;
        }

        .summary {
            display: grid;
            gap: 6px;
            grid-template-columns: repeat(3, 1fr);
            font-size: 12px;
        }

        .summary div {
            border: 1px solid #d1d5db;
            padding: 8px;
        }

        table {
            border-collapse: collapse;
            font-size: 10px;
            width: 100%;
        }

        th,
        td {
            border: 1px solid #d1d5db;
            padding: 6px;
            text-align: left;
            vertical-align: top;
        }

        th {
            background: #f3f4f6;
            color: #0b2341;
        }

        footer {
            border-top: 1px solid #d1d5db;
            margin-top: 20px;
            padding-top: 10px;
        }

        @media print {
            body {
                margin: 12mm;
            }
        }
    </style>
</head>
<body>
    <header>
        <h1>{{ $title }}</h1>
        <p>{{ $lguName }} | PaperTrail</p>
        <p class="meta">Generated by {{ $generatedBy }} on {{ now()->format('F d, Y h:i A') }}</p>
    </header>

    <section class="filters" aria-label="Report filters">
        @foreach ($filters as $label => $value)
            <p><strong>{{ $label }}:</strong> {{ $value }}</p>
        @endforeach
    </section>

    <section class="summary" aria-label="Accounting report summary">
        <div><strong>Total Documents Processed:</strong> {{ $summary['totalProcessed'] }}</div>
        <div><strong>Pending Accounting Review:</strong> {{ $summary['pendingAccountingReview'] }}</div>
        <div><strong>Accounting Verified:</strong> {{ $summary['accountingVerified'] }}</div>
        <div><strong>Returned by Accounting:</strong> {{ $summary['returnedByAccounting'] }}</div>
        <div><strong>Forwarded to BAC Secretariat:</strong> {{ $summary['forwardedToBac'] }}</div>
        <div><strong>Total Amount Reviewed:</strong> PHP {{ number_format($summary['totalAmountReviewed'], 2) }}</div>
    </section>

    <h2>Accounting Review Summary</h2>
    <table>
        <thead>
            <tr>
                @foreach ($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $document)
                @php
                    $latestReview = $document->accountingReviews
                        ->sortByDesc(fn ($review) => $review->completed_at ?? $review->created_at)
                        ->first();
                    $reviewedBy = $document->accountingReviewedBy?->name ?? $latestReview?->reviewedBy?->name ?? 'N/A';
                    $reviewedDate = $document->accounting_reviewed_at ?? $latestReview?->completed_at;
                @endphp
                <tr>
                    <td>{{ $document->tracking_number }}</td>
                    <td>{{ $document->document_type }}</td>
                    <td>{{ $document->title }}</td>
                    <td>{{ $document->submittingOffice?->name ?? 'N/A' }}</td>
                    <td>PHP {{ number_format((float) $document->total_amount, 2) }}</td>
                    <td>{{ $document->budget_status ? str($document->budget_status)->replace('_', ' ')->title() : 'N/A' }}</td>
                    <td>{{ $document->accounting_status ? str($document->accounting_status)->replace('_', ' ')->title() : 'N/A' }}</td>
                    <td>{{ str($document->status)->replace('_', ' ')->title() }}</td>
                    <td>{{ $document->account_code ?? 'N/A' }}</td>
                    <td>{{ $document->object_code ?? 'N/A' }}</td>
                    <td>{{ $document->responsibility_center ?? 'N/A' }}</td>
                    <td>{{ $reviewedBy }}</td>
                    <td>{{ $reviewedDate?->format('M d, Y h:i A') ?? 'N/A' }}</td>
                    <td>{{ $document->currentOffice?->name ?? 'N/A' }}</td>
                    <td>{{ $document->stage ?? 'N/A' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($headers) }}">No accounting report records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <footer>PaperTrail Internal Report</footer>

    <script>
        window.addEventListener('load', () => window.print());
    </script>
</body>
</html>
