<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $title }} | PaperTrail</title>
    <style>
        body {
            color: #0b2341;
            font-family: Arial, sans-serif;
            margin: 28px;
        }

        header {
            border-bottom: 2px solid #0b2341;
            margin-bottom: 18px;
            padding-bottom: 12px;
        }

        h1 {
            font-size: 22px;
            margin: 0 0 4px;
        }

        p {
            margin: 0;
        }

        .meta,
        .filters {
            color: #4b5563;
            font-size: 12px;
            line-height: 1.5;
        }

        .filters {
            margin: 12px 0 18px;
        }

        table {
            border-collapse: collapse;
            font-size: 11px;
            width: 100%;
        }

        th,
        td {
            border: 1px solid #d1d5db;
            padding: 7px;
            text-align: left;
            vertical-align: top;
        }

        th {
            background: #f3f4f6;
            color: #0b2341;
        }

        @media print {
            body {
                margin: 14mm;
            }
        }
    </style>
</head>
<body>
    <header>
        <h1>{{ $title }}</h1>
        <p>{{ $lguName }} | PaperTrail</p>
        <p class="meta">Generated by {{ $generatedBy }} on {{ now()->format('F d, Y h:i A') }}</p>
    </header>

    <section class="filters" aria-label="Report filters">
        @foreach ($filters as $label => $value)
            <p><strong>{{ $label }}:</strong> {{ $value }}</p>
        @endforeach
    </section>

    <table>
        <thead>
            <tr>
                @foreach ($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $document)
                @php
                    $latestReview = $document->budgetReviews
                        ->sortByDesc(fn ($review) => $review->completed_at ?? $review->created_at)
                        ->first();
                    $reviewedBy = $document->budgetReviewedBy?->name ?? $latestReview?->reviewedBy?->name ?? 'N/A';
                    $reviewedDate = $document->budget_reviewed_at ?? $latestReview?->completed_at;
                @endphp
                <tr>
                    <td>{{ $document->tracking_number }}</td>
                    <td>{{ $document->document_type }}</td>
                    <td>{{ $document->submittingOffice?->name ?? 'N/A' }}</td>
                    <td>PHP {{ number_format((float) $document->total_amount, 2) }}</td>
                    <td>{{ $document->budget_status ? str($document->budget_status)->replace('_', ' ')->title() : 'N/A' }}</td>
                    <td>{{ $reviewedBy }}</td>
                    <td>{{ $reviewedDate?->format('M d, Y h:i A') ?? 'N/A' }}</td>
                    <td>{{ str($document->status)->replace('_', ' ')->title() }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($headers) }}">No budget report records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <script>
        window.addEventListener('load', () => window.print());
    </script>
</body>
</html>
