<?php

return [
    'bac_resolution' => [
        'signing_mode' => 'parallel',
        'signers' => [
            [
                'slot' => 'prepared_by',
                'label' => 'Prepared By',
                'role_code' => 'bac_secretariat',
                'role_name' => 'BAC Secretariat',
                'account_code' => 'BACSEC-002',
                'order' => 1,
                'required' => true,
            ],
            [
                'slot' => 'bac_chairperson',
                'label' => 'BAC Chairperson',
                'role_code' => 'bac_chair',
                'role_name' => 'BAC Chair',
                'account_code' => 'BACCHAIR-001',
                'order' => 2,
                'required' => true,
            ],
            [
                'slot' => 'bac_vice_chairperson',
                'label' => 'BAC Vice Chairperson',
                'role_code' => 'bac_vice_chairperson',
                'role_name' => 'BAC Vice Chairperson',
                'account_code' => 'BACVICE-001',
                'order' => 3,
                'required' => true,
            ],
            [
                'slot' => 'bac_member_1',
                'label' => 'BAC Member',
                'role_code' => 'bac_member',
                'role_name' => 'BAC Member',
                'account_code' => 'BACMEM-001',
                'order' => 4,
                'required' => true,
            ],
            [
                'slot' => 'bac_member_2',
                'label' => 'BAC Member',
                'role_code' => 'bac_member',
                'role_name' => 'BAC Member',
                'account_code' => 'BACMEM-002',
                'order' => 5,
                'required' => true,
            ],
            [
                'slot' => 'bac_provisional_member',
                'label' => 'BAC Member',
                'role_code' => 'bac_member',
                'role_name' => 'BAC Member',
                'account_code' => 'BACMEM-003',
                'order' => 6,
                'required' => true,
            ],
            [
                'slot' => 'hope',
                'label' => 'Approved By',
                'role_code' => 'approving_authority',
                'role_name' => 'HOPE / Municipal Mayor',
                'account_code' => 'HOPE-001',
                'office_code' => 'MO',
                'office_names' => ['Office of the Municipal Mayor'],
                'order' => 7,
                'required' => true,
            ],
        ],
    ],
];
